version: '3.4'

services:
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: 
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
  jobmanager:
    container_name: job-manager-app
    image: ${DOCKER_REGISTRY-}jobmanager
    build: 
      context: .
      dockerfile: JobManager/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - sql
    environment:
      - DB_HOST=sql
      - DB_NAME=JobManagerDb
      - DB_SA_PASSWORD=password@12345#
      
